name: ocqsvm
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12,<=3.13
  - pip  
  - matplotlib
  - notebook
  - numpy
  - qiskit>=1.4
  - pandas
  - tqdm
  - pylatexenc
  - msal
  - seaborn
  - scipy
  - scikit-learn
  - networkx
  - tqdm
  - pyod
  - pip:
    - qiskit-ibm-runtime>=0.40.0, <=0.41.0
    - qiskit-aer>=0.17.0, <=0.18
    - qiskit-machine-learning>=0.8.0, <=0.9.0
    - openpyxl>=3.1.4
